### PR TITLE
Fix doubled first occurrence of recurring event

### PR DESCRIPTION
**Pull request by petschki**

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
I have restored the mr.roboto / Jenkins hooks.  Let's see if they listen to this comment again:

@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
Well, that started four Jenkins jobs, but they all fail within a few seconds:

Could not update Pull Request https://github.com/plone/plone.app.event/pull/1
Please contact the testing team: https://github.com/orgs/plone/teams/testing-team
Fill an issue as well: https://github.com/plone/jenkins.plone.org/issues/new

I will do that.

**Comment by mauritsvanrees** [comment]
@petschki Could you recreate your PR on the plone.app.event repo please?

The repo was accidentally removed at the end of the Alpine City Sprint.  We restored it, but the issues and PRs were lost.  After contact with GitHub, we renamed it to `plone.app.event.renamedforrestore` so GitHub could restore the original repo including issues and PRs.

So now your PR is on this `renamedforrestore` repo which we should remove soon.  Go to your branch, push it, and create a PR, and all should be well again I think.

**Comment by petschki** [comment]
the PR is already there https://github.com/plone/plone.app.event/pull/349 ... 👍🏼

**Comment by mauritsvanrees** [comment]
Ah, good, thanks.
I will archive this temporary repo and then we will remove it soon.

**Pull request closed without merging**
